version: "3"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - REPLICATE_API_TOKEN=${REPLICATE_API_TOKEN}

  frontend:
    build: ./frontend
    ports:
      - "80:3000"
    depends_on:
      - backend
